# Generated by Django 5.0.6 on 2024-06-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('content', models.TextField()),
                ('nouns', models.TextField()),
                ('verbs', models.TextField()),
            ],
        ),
    ]
